package service

import (
	"appgraph/db"
	"context"
	"log"
	"os/exec"
	"time"

	"github.com/spf13/cobra"
)

var GenerateSbomCmd = &cobra.Command{
	Use:   "gen-sbom",
	Short: "Generate and register an SBOM for your service",
	Long:  ``,
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		result, err := GenerateSbom(args[0])
		if err != nil {
			return err
		}

		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()

		dbClient, err := db.NewPostgres(ctx)
		if err != nil {
			return err
		}

		err = dbClient.RegisterSbom(ctx, serviceId, result)
		if err != nil {
			return err
		}

		log.Println(result)

		return nil
	},
}

var serviceId int

func init() {
	GenerateSbomCmd.Flags().IntVar(&serviceId, "id", 0, "Enter your service ID generated by AppGraph")
	GenerateSbomCmd.MarkFlagRequired("id")
}

func GenerateSbom(loc string) (string, error) {
	output := exec.Command("syft", "-o", "json", loc)
	result, err := output.Output()
	if err != nil {
		return "", err
	}
	return string(result), nil
}

// Generate SBOM
// Name the SBOM file per the service name - id
// Sign
// Upload

// ag svc gen-sbom --id 123
